// Re-export types and functions from PostgreSQL storage
// This file now uses PostgreSQL instead of file storage
export {
  extractAssistantId,
  createCall,
  readCall,
  readCallByOrganization,
  updateCall,
  findCallByCallId,
  findCallByCallIdByOrganization,
  createOrder,
  readOrder,
  updateOrder,
  findOrderByOrderId,
  findOrderByOrderIdByOrganization,
  listCalls,
  listCallsByOrganization,
  listOrders,
  listOrdersByOrganization,
  updateOrderStatusByOrganization,
  getOrderStatsByOrganization,
  type Call,
  type Order,
  type OrderStatus,
} from "./vapi-storage-db";
